If modifying a VFS with newer iVersion we lower the version to the maximum supported version of this code.
Originally, the code returned SQLITE_ERROR which causes the following
exception on the Python side:

OperationalError: SQL logic error or missing database

This is hard to debug and currently falling back does only disable mmap which
is of no use for us anyway at this time.